'use strict';
import { parseVrpacsManifest, bestDetectedRequest, seriesFolderName, sanitizeSegment } from '../pacs.js';
function toUrl(id,host){let s=String(id||'');for(const p of ['wadouri:','wadors:','dicomweb:','dicomfile:'])if(s.startsWith(p)){s=s.slice(p.length);break;}return /^https?:/i.test(s)?s:`${host}/${s.replace(/^\//,'')}`;}
export const VrpacsAdapter={
  id:'VRPACS',
  match(summary){return summary?.detector==='VRPACS'||Boolean(bestDetectedRequest(summary?.requests||[],['VRPACS_MANIFEST']));},
  async analyze(ctx){const hit=bestDetectedRequest(ctx.summary.requests,['VRPACS_MANIFEST']);if(!hit)throw new Error('Chưa thấy manifest VRPACS.');const payload=await ctx.fetchJson(hit.url,'application/json',hit);const p=parseVrpacsManifest(payload);const st=p.studies?.[0]||{};return ctx.normalizeStudy({adapter:'VRPACS',studyUid:String(st.studyInstanceUID||st.StudyInstanceUID||st.studyUid||st.StudyInsUID||st.studyUID||''),patient:p.patient,series:p.series,context:{manifestUrl:hit.url,host:new URL(hit.url).origin,completeKnown:true}});},
  async enumerate(inv,selected,ctx){const state=ctx.state,req=(state.pacsRequests||[]).find(x=>x.type==='VRPACS_MANIFEST'&&x.url===inv.context.manifestUrl);const p=parseVrpacsManifest(await ctx.fetchJson(inv.context.manifestUrl,'application/json',req));const set=new Set(selected),tasks=[];for(let i=0;i<p.rawSeries.length;i++){const raw=p.rawSeries[i],choice=p.series[i];if(!set.has(choice.id))continue;const folder=seriesFolderName(choice,i);let k=0;for(const id of (raw.imageIds||[])){if(!id)continue;k++;const url=toUrl(id,inv.context.host);tasks.push({strategy:'fetch-dicom',url,headers:ctx.headersForUrl(url),method:'GET',studyUid:inv.studyUid,seriesUid:choice.seriesUid||'',sopInstanceUid:'',relativePath:`${folder}/IM_${String(k).padStart(5,'0')}_${sanitizeSegment(String(id).split('/').pop()?.slice(-28)||String(k),'image')}.dcm`});}}return tasks;}
};
