'use strict';
const $=id=>document.getElementById(id),show=(id,on)=>$(id).classList.toggle('hidden',!on);const TERMINAL=new Set(['done','partial','done_with_errors','error','cancelled']);
let tabId=null,summary=null,state=null,inventory=null,job=null,history=[],revealDownloaded=false,refreshTimer=null,activeTabUrl='';
const FS_DB='pacs_dicom_fs_v1',FS_STORE='handles',FS_KEY='download-root';

async function send(type,payload={}){const r=await chrome.runtime.sendMessage({type,...payload});if(!r?.ok)throw new Error(r?.error||'Lỗi extension');return r;}
function toast(text,bad=false){const e=$('toast');e.textContent=text;e.classList.toggle('error',bad);e.classList.remove('hidden');setTimeout(()=>e.classList.add('hidden'),2600);}
function fmtName(x){return String(x||'').replace(/\^+/g,' ').replace(/\s+/g,' ').trim();}
function fmtDate(x){const d=String(x||'').replace(/[^0-9]/g,'');return d.length>=8?`${d.slice(6,8)}/${d.slice(4,6)}/${d.slice(0,4)}`:(x||'—');}
function fmtWhen(x){if(!x)return'';return new Date(x).toLocaleString('vi-VN',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'});}
function chip(el,text,kind='neutral'){el.textContent=text;el.className=`chip ${kind}`;}
function patternFor(url){try{const u=new URL(url);return`${u.protocol}//${u.host}/*`;}catch{return'';}}

function openFsDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open(FS_DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(FS_STORE))r.result.createObjectStore(FS_STORE);};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function fsGet(){const db=await openFsDb();try{return await new Promise((resolve,reject)=>{const tx=db.transaction(FS_STORE,'readonly'),r=tx.objectStore(FS_STORE).get(FS_KEY);r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error);});}finally{db.close();}}
async function fsSet(h){const db=await openFsDb();try{await new Promise((resolve,reject)=>{const tx=db.transaction(FS_STORE,'readwrite');tx.objectStore(FS_STORE).put(h,FS_KEY);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});}finally{db.close();}}
async function ensureFolder(interactive=false){let h=await fsGet();if(!h&&interactive){h=await window.showDirectoryPicker({mode:'readwrite'});await fsSet(h);}if(!h)return null;let p=typeof h.queryPermission==='function'?await h.queryPermission({mode:'readwrite'}):'granted';if(p!=='granted'&&interactive&&typeof h.requestPermission==='function')p=await h.requestPermission({mode:'readwrite'});if(p!=='granted')return null;return h;}
async function renderFolder(){try{const h=await ensureFolder(false);$('folderText').textContent=h?`${h.name} / PACS_DICOM`:'Chưa chọn';}catch{$('folderText').textContent='Chưa chọn';}}

async function grantAccess(){let pats=[...(summary?.missingOrigins||[])];if(!pats.length){const p=patternFor(activeTabUrl);if(p)pats=[p];}if(!pats.length)return;const ok=await chrome.permissions.request({origins:pats});if(!ok)return toast('Chưa cấp quyền site.',true);await send('SITE_ACCESS_CHANGED',{tabId});toast('Đã cấp quyền.');await refresh();}

function renderStatus(){const conf=Number(summary?.confidence||state?.confidence||0),ready=Boolean(inventory?.series?.length),missing=summary?.missingOrigins||[];$('scoreText').textContent=conf?`${conf}%`:'';if(ready){$('statusTitle').textContent='Sẵn sàng';$('statusText').textContent=`${inventory.adapter} · ${inventory.series.length} series`;chip($('siteChip'),'PACS','good');}else if(state?.tracking==='watching'){$('statusTitle').textContent='Đang theo dõi';$('statusText').textContent='Chờ manifest hoặc DICOM từ viewer';chip($('siteChip'),'Theo dõi','warn');}else if(state?.tracking==='candidate'||conf>=55){$('statusTitle').textContent='Có thể là PACS';$('statusText').textContent=missing.length?'Cấp quyền site để phân tích':'Bấm Theo dõi tab';chip($('siteChip'),'PACS?','warn');}else if(state?.tracking==='stopped'){$('statusTitle').textContent='Đã dừng';$('statusText').textContent='Tab này không được theo dõi';chip($('siteChip'),'Dừng','neutral');}else{$('statusTitle').textContent='Không phát hiện PACS';$('statusText').textContent='Có thể bật theo dõi thủ công cho tab này';chip($('siteChip'),'Tab thường','neutral');}show('permissionBox',missing.length>0);$('permissionText').textContent=missing.length>1?`Cần quyền ${missing.length} site`:'Cần quyền truy cập site';$('trackBtn').textContent=state?.tracking==='watching'?'Dừng theo dõi':'Theo dõi tab';show('deepScanBtn',!ready&&state?.tracking==='watching'&&!missing.length&&Boolean(state?.binaryCandidates?.length));}

function previousDone(){return inventory?.previousDownload?.status==='done';}
function renderInventory(){if(!inventory){show('doneCard',false);show('studyCard',false);show('seriesCard',false);show('stickyBar',false);return;}if(previousDone()&&!revealDownloaded){show('doneCard',true);show('studyCard',false);show('seriesCard',false);show('stickyBar',false);$('doneMeta').textContent=`${fmtName(inventory.patient?.name)||'Study'} · ${fmtDate(inventory.patient?.studyDate)}${inventory.previousDownload?.lastDownloadAt?` · ${fmtWhen(inventory.previousDownload.lastDownloadAt)}`:''}`;return;}show('doneCard',false);show('studyCard',true);show('seriesCard',true);show('stickyBar',true);$('studySub').textContent=inventory.studyUid||inventory.patient?.description||'—';chip($('adapterChip'),inventory.adapter||'DICOM','good');$('patientName').textContent=fmtName(inventory.patient?.name)||'—';$('patientId').textContent=inventory.patient?.id||'—';$('studyDate').textContent=fmtDate(inventory.patient?.studyDate);$('seriesCount').textContent=String(inventory.series?.length||0);const prev=inventory.previousDownload;show('partialBanner',Boolean(prev&&prev.status!=='done'&&prev.lastDownloadAt));if(prev&&prev.status!=='done'&&prev.lastDownloadAt)$('partialBanner').textContent=`Lần trước: ${prev.completed||0}/${prev.total||'?'} ảnh · tải lại sẽ bỏ qua file đã có.`;const list=$('seriesList');list.textContent='';for(const s of(inventory.series||[])){const row=document.createElement('label');row.className='series-row';const cb=document.createElement('input');cb.type='checkbox';cb.checked=true;cb.dataset.id=s.id;cb.addEventListener('change',updateSelected);const main=document.createElement('div');main.className='series-main';const title=document.createElement('div');title.className='series-title';title.textContent=`${s.number?`${s.number} · `:''}${s.description||'Series'}`;const meta=document.createElement('div');meta.className='series-meta';const m1=document.createElement('span');m1.textContent=s.modality||'DICOM';const m2=document.createElement('span');m2.textContent=s.sequenceHint||'';meta.append(m1,m2);main.append(title,meta);const count=document.createElement('span');count.className='series-count';count.textContent=s.imageCount?`${s.imageCount} ảnh`:'? ảnh';row.append(cb,main,count);list.append(row);}updateSelected();}
function selectedIds(){return[...$('seriesList').querySelectorAll('input[type=checkbox]:checked')].map(x=>x.dataset.id);}
function updateSelected(){const ids=selectedIds(),sel=(inventory?.series||[]).filter(s=>ids.includes(s.id)),images=sel.reduce((n,s)=>n+(Number(s.imageCount)||0),0);$('selectedSummary').textContent=`${ids.length}/${inventory?.series?.length||0} series${images?` · ~${images} ảnh`:''}`;$('stickyTitle').textContent=`${ids.length} series${images?` · ~${images} ảnh`:''}`;$('stickySub').textContent='Tên - ID - Ngày / Series';$('downloadBtn').disabled=!ids.length;$('downloadBtn').textContent=inventory?.previousDownload&&inventory.previousDownload.status!=='done'?'Tải phần thiếu':'Tải DICOM';}

function jobLabel(s){return({preparing:'Chuẩn bị',downloading:'Đang tải',done:'Hoàn tất',partial:'Đã lưu',done_with_errors:'Có lỗi',error:'Lỗi',cancelling:'Đang dừng',cancelled:'Đã dừng'})[s]||s||'—';}
function renderJob(){if(!job||Number(job.tabId)!==Number(tabId)){show('progressCard',false);return;}show('progressCard',true);const total=Number(job.total)||0,done=Number(job.completed||0)+Number(job.failed||0),pct=total?Math.min(100,Math.round(done*100/total)):0;$('progressBar').style.width=`${pct}%`;$('progressText').textContent=`${done} / ${total||'?'}`;$('failedText').textContent=`${job.failed||0} lỗi${job.skipped?` · ${job.skipped} có sẵn`:''}`;$('currentFile').textContent=job.currentFile||'';$('jobTitle').textContent=job.status==='partial'?'Đã lưu dữ liệu bắt được':job.status==='done'?'Tải hoàn tất':job.status==='done_with_errors'?'Hoàn tất có lỗi':'Đang tải DICOM';$('jobMeta').textContent=`${job.adapter||'DICOM'}${job.original||job.reconstructed?` · ${job.original||0} gốc${job.reconstructed?` · ${job.reconstructed} dựng lại`:''}`:''}`;const kind=job.status==='done'?'good':['error','done_with_errors'].includes(job.status)?'bad':['partial','cancelled'].includes(job.status)?'warn':'neutral';chip($('jobBadge'),jobLabel(job.status),kind);$('cancelBtn').disabled=!['preparing','downloading','cancelling'].includes(job.status);const errs=job.errors||[];show('errorDetails',errs.length>0);$('errorLog').textContent=errs.join('\n');if(TERMINAL.has(job.status)){refreshHistory().catch(()=>{});setTimeout(refresh,250);}}

function historyStatus(s){return({done:'Đã tải',partial:'Đã lưu',done_with_errors:'Có lỗi',error:'Lỗi',cancelled:'Đã dừng',viewed:'Đã xem'})[s]||'Đã xem';}
function renderHistory(){const q=$('historySearch').value.trim().toLowerCase(),el=$('historyList');el.textContent='';const rows=history.filter(h=>!q||`${h.patientName||''} ${h.patientId||''} ${h.studyDate||''} ${h.description||''}`.toLowerCase().includes(q));if(!rows.length){el.innerHTML='<div class="empty">Chưa có kết quả.</div>';return;}for(const h of rows.slice(0,70)){const item=document.createElement('div');item.className='history-item';const top=document.createElement('div');top.className='history-top';const left=document.createElement('div'),name=document.createElement('div');name.className='history-name';name.textContent=`${fmtName(h.patientName)||'Unknown'}${h.patientId?` · ${h.patientId}`:''}`;const meta=document.createElement('div');meta.className='history-meta';meta.textContent=`${fmtDate(h.studyDate)}${h.seriesCount?` · ${h.seriesCount} series`:''}${h.lastDownloadAt?` · ${fmtWhen(h.lastDownloadAt)}`:''}`;left.append(name,meta);const st=document.createElement('span');st.className=`history-status ${h.status==='done'?'done':['error','done_with_errors'].includes(h.status)?'bad':''}`;st.textContent=historyStatus(h.status);top.append(left,st);item.append(top);el.append(item);}}
async function refreshHistory(){try{history=(await send('GET_HISTORY')).history||[];renderHistory();}catch{}}

async function refresh(){if(tabId==null)return;try{const r=await send('GET_OVERVIEW',{tabId});summary=r.summary;state=r.state;inventory=r.inventory;job=r.job;renderStatus();renderInventory();renderJob();}catch(e){$('statusText').textContent=e.message||String(e);}await renderFolder();}
async function bindActive(){const t=(await chrome.tabs.query({active:true,currentWindow:true}))[0];if(!t?.id)return;tabId=t.id;activeTabUrl=t.url||'';$('tabLabel').textContent=t.title||t.url||`Tab ${tabId}`;revealDownloaded=false;await refresh();}
function scheduleRefresh(ms=180){clearTimeout(refreshTimer);refreshTimer=setTimeout(()=>refresh().catch(()=>{}),ms);}

async function startDownload(){if(!selectedIds().length)return;try{const h=await ensureFolder(true);if(!h)return toast('Chưa có quyền ghi thư mục.',true);await renderFolder();const r=await send('START_DOWNLOAD',{tabId,selectedSeries:selectedIds(),options:{concurrency:6,frameConcurrency:6}});job=r.job;renderJob();}catch(e){toast(e.message||String(e),true);}}

$('grantBtn').addEventListener('click',()=>grantAccess().catch(e=>toast(e.message||String(e),true)));
$('folderBtn').addEventListener('click',async()=>{try{const h=await window.showDirectoryPicker({mode:'readwrite'});await fsSet(h);await renderFolder();}catch(e){if(e?.name!=='AbortError')toast(e.message||String(e),true);}});
$('trackBtn').addEventListener('click',async()=>{try{if(state?.tracking==='watching')await send('STOP_TRACKING',{tabId});else{if((summary?.missingOrigins||[]).length)await grantAccess();await send('START_TRACKING',{tabId});}await refresh();}catch(e){toast(e.message||String(e),true);}});
$('scanBtn').addEventListener('click',async()=>{try{await send('ANALYZE_TAB',{tabId});await refresh();}catch(e){toast(e.message||String(e),true);}});
$('deepScanBtn').addEventListener('click',async()=>{try{const r=await send('DEEP_SCAN',{tabId});toast(r.valid?.length?`Đã nhận diện ${r.valid.length} endpoint DICOM.`:'Chưa xác nhận được endpoint DICOM.',!r.valid?.length);await refresh();}catch(e){toast(e.message||String(e),true);}});
$('selectAllBtn').addEventListener('click',()=>{$('seriesList').querySelectorAll('input').forEach(x=>x.checked=true);updateSelected();});
$('selectNoneBtn').addEventListener('click',()=>{$('seriesList').querySelectorAll('input').forEach(x=>x.checked=false);updateSelected();});
$('downloadBtn').addEventListener('click',startDownload);
$('cancelBtn').addEventListener('click',()=>send('CANCEL_JOB',{tabId}).then(()=>scheduleRefresh(100)).catch(e=>toast(e.message||String(e),true)));
$('revealDownloadedBtn').addEventListener('click',()=>{revealDownloaded=true;renderInventory();});
$('historyOpenBtn').addEventListener('click',async()=>{show('historyCard',true);$('historyToggle').querySelector('span').textContent='⌄';await refreshHistory();});
$('historyToggle').addEventListener('click',async()=>{const open=$('historyCard').classList.contains('hidden');show('historyCard',open);$('historyToggle').querySelector('span').textContent=open?'⌄':'›';if(open)await refreshHistory();});
$('historySearch').addEventListener('input',renderHistory);
$('clearHistoryBtn').addEventListener('click',async()=>{await send('CLEAR_HISTORY');await refreshHistory();});
chrome.tabs.onActivated.addListener(()=>bindActive().catch(()=>{}));chrome.tabs.onUpdated.addListener((id,change,tab)=>{if(id===tabId&&(change.url||change.title||change.status==='complete')){activeTabUrl=tab.url||activeTabUrl;$('tabLabel').textContent=tab.title||tab.url||`Tab ${id}`;scheduleRefresh(150);}});
chrome.runtime.onMessage.addListener(m=>{if(['JOB_UPDATED','INVENTORY_UPDATED','PACS_SIGNAL','TAB_CONTEXT_CHANGED'].includes(m?.type)&&Number(m.tabId)!==Number(tabId))return;if(m?.type==='JOB_UPDATED'){job=m.job;renderJob();}else if(m?.type==='INVENTORY_UPDATED'){inventory=m.inventory;renderInventory();scheduleRefresh(80);}else if(['PACS_SIGNAL','TAB_CONTEXT_CHANGED'].includes(m?.type))scheduleRefresh(180);else if(m?.type==='HISTORY_UPDATED'){history=m.history||[];if(!$('historyCard').classList.contains('hidden'))renderHistory();}});
bindActive().then(refreshHistory).catch(e=>toast(e.message||String(e),true));
