'use strict';
import { bestDetectedRequest, deriveDicomweb, parseDicomwebSeries, dicomJsonValue, seriesFolderName, sanitizeSegment, fetchQidoPaged } from '../pacs.js';
const JSON_ACCEPT='application/dicom+json, application/json';
const sopKey=x=>String(dicomJsonValue(x,'00080018')||'').trim();
/** Read all QIDO instances endpoint with automatic pagination. */
const allInstances=(ctx,url)=>fetchQidoPaged((u,a)=>ctx.fetchJson(u,a),url,{accept:JSON_ACCEPT,keyOf:sopKey});
function uid(inst,tag){return String(dicomJsonValue(inst,tag)||'').trim();}
function frames(inst){return Math.max(1,Number(dicomJsonValue(inst,'00280008')||1)||1);}
function patient(meta){const pn=dicomJsonValue(meta,'00100010');return{name:pn&&typeof pn==='object'?(pn.Alphabetic||''):String(pn||''),id:String(dicomJsonValue(meta,'00100020')||''),birthDate:String(dicomJsonValue(meta,'00100030')||''),studyDate:String(dicomJsonValue(meta,'00080020')||''),description:String(dicomJsonValue(meta,'00081030')||''),accession:String(dicomJsonValue(meta,'00080050')||'')};}
export const DicomwebAdapter={
  id:'DICOMWEB',
  match(summary){return summary?.detector==='DICOMWEB'||Boolean(bestDetectedRequest(summary?.requests||[],['QIDO_SERIES','QIDO_INSTANCES','DICOM_METADATA','DICOM_INSTANCE','DICOM_FRAME','WADO']));},
  async analyze(ctx){const qido=bestDetectedRequest(ctx.summary.requests,['QIDO_SERIES']);const seed=qido?.url||bestDetectedRequest(ctx.summary.requests,['QIDO_INSTANCES','DICOM_METADATA','DICOM_INSTANCE','DICOM_FRAME','WADO'])?.url;const d=deriveDicomweb(seed);if(!d)throw new Error('Unable to extract StudyInstanceUID from DICOMweb.');const seriesUrl=qido?.url||ctx.inheritQuery(`${d.rsBase}/studies/${encodeURIComponent(d.studyUid)}/series`,seed);const raw=await ctx.fetchJson(seriesUrl,'application/dicom+json, application/json');const series=parseDicomwebSeries(raw);const enriched=[];for(const s of series){let count=s.imageCount;if(!count){try{const arr=await allInstances(ctx,ctx.inheritQuery(`${d.rsBase}/studies/${encodeURIComponent(d.studyUid)}/series/${encodeURIComponent(s.seriesUid)}/instances`,seriesUrl));count=arr.length;}catch{}}enriched.push({...s,imageCount:count});}let p={name:'',id:'',birthDate:'',studyDate:'',description:'',accession:''};try{const st=await ctx.fetchJson(ctx.inheritQuery(`${d.rsBase}/studies/${encodeURIComponent(d.studyUid)}`,seriesUrl),'application/dicom+json, application/json');p=patient(Array.isArray(st)?(st[0]||{}):st);}catch{}const wado=bestDetectedRequest(ctx.summary.requests,['WADO']);return ctx.normalizeStudy({adapter:'DICOMWEB',studyUid:d.studyUid,patient:p,series:enriched,context:{rsBase:d.rsBase,seriesUrl,studyUid:d.studyUid,wadoTemplate:wado?.url||'',completeKnown:true}});},
  async enumerate(inv,selected,ctx){const set=new Set(selected),tasks=[];const rs=inv.context.rsBase,study=inv.context.studyUid,q=inv.context.seriesUrl;let wado=null;try{wado=inv.context.wadoTemplate?new URL(inv.context.wadoTemplate):null;}catch{}let studyWide=null;async function getWide(){if(studyWide)return studyWide;studyWide={};for(const ep of [`${rs}/studies/${encodeURIComponent(study)}/instances`,`${rs}/studies/${encodeURIComponent(study)}/metadata`]){try{const a=ep.endsWith('/metadata')?await ctx.fetchJson(ctx.inheritQuery(ep,q),JSON_ACCEPT):await allInstances(ctx,ctx.inheritQuery(ep,q));if(!Array.isArray(a)||!a.length)continue;for(const x of a){const su=uid(x,'0020000E');if(su)(studyWide[su] ||= []).push(x);}if(Object.keys(studyWide).length)break;}catch{}}return studyWide;}
    for(let si=0;si<inv.series.length;si++){const s=inv.series[si];if(!set.has(s.id))continue;const folder=seriesFolderName(s,si),instancesUrl=ctx.inheritQuery(`${rs}/studies/${encodeURIComponent(study)}/series/${encodeURIComponent(s.seriesUid)}/instances`,q);let inst=[];try{inst=await allInstances(ctx,instancesUrl);}catch{}if(!Array.isArray(inst))inst=[];if(!inst.length||(s.imageCount&&inst.length<s.imageCount)){try{const m=await ctx.fetchJson(ctx.inheritQuery(`${rs}/studies/${encodeURIComponent(study)}/series/${encodeURIComponent(s.seriesUid)}/metadata`,q),'application/dicom+json, application/json');if(Array.isArray(m)&&m.length>inst.length)inst=m;}catch{}}if(!inst.length||(s.imageCount&&inst.length<s.imageCount)){const g=await getWide();if((g[s.seriesUid]||[]).length>inst.length)inst=g[s.seriesUid];}const unique=new Map();for(const x of inst){const i=uid(x,'00080018');if(i)unique.set(i,x);}inst=[...unique.values()];if(s.imageCount&&inst.length<s.imageCount)throw new Error(`Series ${s.number||si+1}: ${inst.length}/${s.imageCount} instances.`);let k=0;for(const x of inst){const iuid=uid(x,'00080018');if(!iuid)continue;k++;const base=ctx.inheritQuery(`${rs}/studies/${encodeURIComponent(study)}/series/${encodeURIComponent(s.seriesUid)}/instances/${encodeURIComponent(iuid)}`,q);let primaryUrl='';if(wado){const u=new URL(wado.href);u.searchParams.set('requestType','WADO');u.searchParams.set('studyUID',study);u.searchParams.set('seriesUID',s.seriesUid);u.searchParams.set('objectUID',iuid);u.searchParams.set('contentType','application/dicom');u.searchParams.set('transferSyntax','*');primaryUrl=u.href;}tasks.push({strategy:'dicomweb-instance',url:primaryUrl,instanceBase:base,meta:x,numberOfFrames:frames(x),headers:ctx.headersForUrl(primaryUrl||base),studyUid:study,seriesUid:s.seriesUid,sopInstanceUid:iuid,relativePath:`${folder}/IM_${String(k).padStart(5,'0')}_${sanitizeSegment(iuid.slice(-24),'uid')}.dcm`});}}
    return tasks;
  }
};

